from __future__ import annotations

import os
import shutil
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any

from app.config import settings


class DouyinCookieError(RuntimeError):
    pass


_PROCESS_REFRESH_LOCK = threading.Lock()
_CACHE_DIR = Path(".cache")
_COOKIE_FILE = _CACHE_DIR / "douyin-dev-cookies.txt"
_USER_AGENT_FILE = _CACHE_DIR / "douyin-dev-user-agent.txt"
_REFRESH_LOCK_FILE = _CACHE_DIR / "douyin-cookie-refresh.lock"


def _is_fresh(destination: Path, user_agent_file: Path) -> bool:
    return (
        destination.is_file()
        and user_agent_file.is_file()
        and time.time() - destination.stat().st_mtime
        < settings.douyin_cookie_max_age_seconds
        and bool(user_agent_file.read_text(encoding="utf-8").strip())
    )


@contextmanager
def _cross_process_refresh_lock(timeout_seconds: float = 45.0):
    """Serialize persistent-browser access across API workers."""
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    deadline = time.monotonic() + timeout_seconds
    while True:
        try:
            descriptor = os.open(
                _REFRESH_LOCK_FILE,
                os.O_CREAT | os.O_EXCL | os.O_WRONLY,
            )
            os.write(descriptor, f"{os.getpid()}\n".encode())
            os.close(descriptor)
            break
        except FileExistsError:
            try:
                stale = time.time() - _REFRESH_LOCK_FILE.stat().st_mtime > 90
                if stale:
                    _REFRESH_LOCK_FILE.unlink(missing_ok=True)
                    continue
            except FileNotFoundError:
                continue
            if time.monotonic() >= deadline:
                raise DouyinCookieError("等待另一个 Cookie 刷新任务超时")
            time.sleep(0.2)
    try:
        yield
    finally:
        _REFRESH_LOCK_FILE.unlink(missing_ok=True)


def _edge_path() -> str:
    candidates = [
        shutil.which("msedge"),
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return candidate
    raise DouyinCookieError("未找到 Microsoft Edge，无法自动刷新抖音开发 Cookie")


def _write_netscape_cookies(cookies: list[dict], destination: Path) -> None:
    lines = ["# Netscape HTTP Cookie File", "# Generated by MiMo Trust dev cookie broker"]
    for cookie in cookies:
        name = cookie.get("name")
        if not name:
            continue
        domain = str(cookie.get("domain") or "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = cookie.get("expires") or 0
        expires = int(expires) if float(expires) > 0 else 0
        lines.append(
            "\t".join(
                [
                    domain,
                    include_subdomains,
                    str(cookie.get("path") or "/"),
                    secure,
                    str(expires),
                    str(name),
                    str(cookie.get("value") or ""),
                ]
            )
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(".tmp")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.replace(temporary, destination)


def get_dev_cookie_file(url: str, force: bool = False) -> tuple[Path, str]:
    """Return a UA-bound Cookie file from a persistent service browser profile.

    Age is only a reuse optimization. The caller validates this session by
    performing the actual extraction and forces one refresh on failure.
    """
    destination = _COOKIE_FILE
    user_agent_file = _USER_AGENT_FILE
    observed_mtime = destination.stat().st_mtime if destination.is_file() else None
    if not force and _is_fresh(destination, user_agent_file):
        return destination, user_agent_file.read_text(encoding="utf-8").strip()

    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise DouyinCookieError(
            "缺少 playwright，无法自动刷新抖音开发 Cookie"
        ) from exc

    with _PROCESS_REFRESH_LOCK, _cross_process_refresh_lock():
        # A concurrent worker may already have replaced the invalid session.
        current_mtime = destination.stat().st_mtime if destination.is_file() else None
        if force and observed_mtime is not None and current_mtime != observed_mtime:
            if _is_fresh(destination, user_agent_file):
                return destination, user_agent_file.read_text(encoding="utf-8").strip()
        elif not force and _is_fresh(destination, user_agent_file):
            return destination, user_agent_file.read_text(encoding="utf-8").strip()

        profile_dir = Path(settings.douyin_browser_profile_dir).resolve()
        profile_dir.mkdir(parents=True, exist_ok=True)
        cookies: list[dict] = []
        user_agent = ""
        title = ""
        final_url = url
        try:
            with sync_playwright() as playwright:
                context = playwright.chromium.launch_persistent_context(
                    user_data_dir=str(profile_dir),
                    executable_path=_edge_path(),
                    headless=settings.douyin_browser_headless,
                    locale="zh-CN",
                    timezone_id="Asia/Shanghai",
                    viewport={"width": 1280, "height": 800},
                    args=["--disable-blink-features=AutomationControlled"],
                )
                try:
                    page = context.pages[0] if context.pages else context.new_page()
                    page.goto(
                        "https://www.douyin.com/",
                        wait_until="domcontentloaded",
                        timeout=30_000,
                    )
                    page.wait_for_timeout(1_500)
                    page.goto(url, wait_until="domcontentloaded", timeout=30_000)
                    for _ in range(2):
                        page.wait_for_timeout(3_000)
                        cookies = context.cookies()
                        if any(c.get("name") == "s_v_web_id" for c in cookies):
                            break
                        page.reload(wait_until="domcontentloaded", timeout=30_000)
                    user_agent = str(page.evaluate("navigator.userAgent"))
                    title = page.title()
                    final_url = page.url
                finally:
                    context.close()
        except Exception as exc:
            raise DouyinCookieError(f"专用浏览器会话刷新失败：{exc}") from exc

        required = {"s_v_web_id", "ttwid"}
        cookie_names = {str(cookie.get("name")) for cookie in cookies}
        missing = sorted(required - cookie_names)
        if missing:
            mode = "无头" if settings.douyin_browser_headless else "可视"
            raise DouyinCookieError(
                f"{mode}专用会话未生成 {', '.join(missing)}；"
                f"页面={title or final_url}。请按 README 的会话引导完成一次验证"
            )
        _write_netscape_cookies(cookies, destination)
        temporary_ua = user_agent_file.with_suffix(".tmp")
        temporary_ua.write_text(user_agent, encoding="utf-8")
        os.replace(temporary_ua, user_agent_file)
        return destination, user_agent


def _url_list(value: Any) -> list[str]:
    if not isinstance(value, dict):
        return []
    raw = value.get("url_list") or value.get("urlList") or []
    if isinstance(raw, dict):
        raw = [raw.get("main_url"), raw.get("backup_url"), raw.get("fallback_url")]
    return [str(item) for item in raw if str(item).startswith(("http://", "https://"))]


def _browser_aweme_info(detail: dict[str, Any], url: str, user_agent: str) -> dict[str, Any]:
    item_id = str(detail.get("aweme_id") or detail.get("awemeId") or "")
    if not item_id:
        raise DouyinCookieError("浏览器作品接口未返回 aweme_id")
    description = str(detail.get("desc") or detail.get("caption") or "").strip()
    author = detail.get("author") or detail.get("authorInfo") or {}
    aweme_type = int(detail.get("aweme_type") or detail.get("awemeType") or 0)
    images: list[dict[str, Any]] = []
    for raw_image in detail.get("images") or detail.get("image_list") or []:
        if not isinstance(raw_image, dict):
            continue
        candidates = _url_list(raw_image)
        if candidates:
            images.append(
                {
                    "url": candidates[0],
                    "fallback_urls": candidates,
                    "width": int(raw_image.get("width") or 0),
                    "height": int(raw_image.get("height") or 0),
                }
            )

    video = detail.get("video") or {}
    formats: list[dict[str, Any]] = []
    for index, bitrate in enumerate(video.get("bit_rate") or []):
        if not isinstance(bitrate, dict):
            continue
        address = bitrate.get("play_addr") or {}
        candidates = _url_list(address)
        # The MP4 variants contain both H.264 video and AAC audio. DASH and
        # H.265 variants are unnecessary for the low-cost ASR path.
        if (
            not candidates
            or str(bitrate.get("format") or "").lower() != "mp4"
            or bool(bitrate.get("is_h265"))
        ):
            continue
        formats.append(
            {
                "format_id": f"browser-mp4-{index}",
                "url": candidates[0],
                "fallback_urls": candidates,
                "ext": "mp4",
                "width": int(address.get("width") or video.get("width") or 0),
                "height": int(address.get("height") or video.get("height") or 0),
                "tbr": float(bitrate.get("bit_rate") or 0) / 1000,
                "filesize": int(address.get("data_size") or 0) or None,
                "vcodec": "h264",
                "acodec": "aac",
            }
        )
    cover_urls = _url_list(video.get("cover") or video.get("origin_cover"))
    is_carousel = aweme_type == 68 or bool(images)
    return {
        "id": item_id,
        "title": description or ("抖音图文作品" if is_carousel else "抖音视频"),
        "description": description,
        "uploader": str(author.get("nickname") or "").strip() or None,
        "duration": (
            None if is_carousel else float(video.get("duration") or detail.get("duration") or 0) / 1000
        ),
        "thumbnail": (images[0]["url"] if images else (cover_urls[0] if cover_urls else None)),
        "webpage_url": f"https://www.douyin.com/{'note' if is_carousel else 'video'}/{item_id}",
        "extractor": "DouyinBrowser",
        "extractor_key": "DouyinBrowser",
        "note_images": images,
        "formats": formats,
        "http_headers": {"User-Agent": user_agent, "Referer": url},
        "_browser_native": True,
    }


def extract_douyin_browser_info(url: str) -> dict[str, Any]:
    """Read signed work data from Douyin's own page request.

    This is the resilient fallback for periods where the yt-dlp extractor no
    longer matches Douyin's current web response. It does not bypass login,
    private-content, DRM, payment, or challenge gates.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise DouyinCookieError("缺少 playwright，无法启动抖音浏览器适配器") from exc

    with _PROCESS_REFRESH_LOCK, _cross_process_refresh_lock():
        profile_dir = Path(settings.douyin_browser_profile_dir).resolve()
        profile_dir.mkdir(parents=True, exist_ok=True)
        try:
            with sync_playwright() as playwright:
                context = playwright.chromium.launch_persistent_context(
                    user_data_dir=str(profile_dir),
                    executable_path=_edge_path(),
                    headless=settings.douyin_browser_headless,
                    locale="zh-CN",
                    timezone_id="Asia/Shanghai",
                    viewport={"width": 1280, "height": 800},
                    args=["--disable-blink-features=AutomationControlled"],
                )
                try:
                    page = context.pages[0] if context.pages else context.new_page()
                    with page.expect_response(
                        lambda response: "/aweme/v1/web/aweme/detail/" in response.url,
                        timeout=45_000,
                    ) as response_info:
                        page.goto(url, wait_until="domcontentloaded", timeout=45_000)
                    response = response_info.value
                    if response.status != 200:
                        raise DouyinCookieError(f"作品接口返回 HTTP {response.status}")
                    payload = response.json()
                    if int(payload.get("status_code") or 0) != 0:
                        raise DouyinCookieError(
                            f"作品接口返回状态 {payload.get('status_code')}"
                        )
                    detail = payload.get("aweme_detail") or payload.get("awemeDetail")
                    if not isinstance(detail, dict):
                        raise DouyinCookieError("作品接口未返回 aweme_detail")
                    user_agent = str(page.evaluate("navigator.userAgent"))
                    cookies = context.cookies()
                    result = _browser_aweme_info(detail, url, user_agent)
                finally:
                    context.close()
        except DouyinCookieError:
            raise
        except Exception as exc:
            raise DouyinCookieError(f"浏览器作品适配器失败：{exc}") from exc

        _write_netscape_cookies(cookies, _COOKIE_FILE)
        temporary_ua = _USER_AGENT_FILE.with_suffix(".tmp")
        temporary_ua.write_text(user_agent, encoding="utf-8")
        os.replace(temporary_ua, _USER_AGENT_FILE)
        return result
